### PR TITLE
keep DoWork Consistent when adjusting message frequency

### PR DESCRIPTION
**Pull request by YoDaMa**
## Purpose
So we move the logic of timing for sending the messages away from just delaying the DoWork loop, and into an if statement. This way, the DoWork is consistently called (the C SDK should have DoWork called with a maximum delay of 100ms between calls), but messages are sent at a specified interval (20 messages per minute, 60 message per minute, etc).

### CODE REVIEW

**Comment by jlian** [comment]
Hi @YoDaMa, since the primary purpose of this sample code is "look how easy it is to modify the default telemetry sample to make it do distributed tracing!" we tried to keep changes to a minimum. As you can see in the [docs](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-distributed-tracing#set-up-device) that it's a 4 line change, where one line is for the connection string, 2 lines are to make the sample run longer, and 1 line is to actually enable distributed tracing.

Thus, I'm a little hesitant to add a big change like this in this sample, because then we would have to explain it, making the doc longer than it already is.

I think I get your concern though, so I have two proposals:

1. Is it possible to achieve what you want with fewer lines of changes (ideally only 1 or 2)? We have to keep it easy to explain in the docs format

2. Can we add a note in the documentation instead, something like "note: this is for demonstration purposes only, for serious scenarios make sure you keep DoWork called with a maximum delay of 100ms between calls"

**Comment by YoDaMa** [comment]
I would say (2) should be a no-go... Whatever we put out there demonstrating use of the SDK should follow the guidelines we set for ourselves so that we don't have people copying the code anyways. I know I'm prone to ignoring 'pls don't copy this code' warnings myself 😄 

What we can do is this: I'm working on migrating the samples to a new repo, so let me tweak the sample to include the code I've offered, so your quickstart stays quick. I'll update this thread when that is done.

**Comment by jlian** [comment]
So you'll tweak the telemetry sample itself? If so I would agree that's the best way to go

**Comment by YoDaMa** [comment]
yep

**Comment by YoDaMa** [comment]
This is old work that is stale.

**Pull request closed without merging**
